import turtle
bob= turtle.Turtle()
bob.pencolor("yellow")
bob.pensize(10)
bob.penup()
bob.setposition(-500,0)
bob.pendown()
bob.forward(100)
bob.left(90)
bob.forward(50)
bob.right(90)
bob.forward(300)
bob.right(90)
bob.forward(50)
bob.left(90)
bob.forward(100)
bob.left(90)
bob.forward(200)
bob.left(90)
bob.forward(100)
bob.left(90)
bob.forward(50)
bob.right(90)
bob.forward(300)
bob.right(90)
bob.forward(50)
bob.left(90)
bob.forward(100)
bob.left(90)
bob.forward(200)
bob.penup()
bob.setposition(-500, -100)
bob.pencolor("red")
bob.write("hot fluid")
bob.pencolor("white")
bob.pendown()
bob.forward(50)
bob.left(90)
bob.pencolor("red")
bob.forward(50)
bob.left(90)
bob.forward(150)
bob.penup()
bob.setposition(-500, -150)
bob.pendown()
bob.pencolor("white")
bob.right(90)
bob.forward(70)
bob.pencolor("blue")
bob.write("cold fluid")
bob.forward(100)
bob.left(90)
bob.forward(200)
bob.pencolor("red")
turtle.done()
